# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature_vectors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='feature_vectors.proto',
  package='revelio',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x66\x65\x61ture_vectors.proto\x12\x07revelio\"p\n\x13StatisticalMeasures\x12\x0b\n\x03\x61vg\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\x12\x0e\n\x06median\x18\x03 \x01(\x02\x12\x0e\n\x06\x66irstq\x18\x04 \x01(\x02\x12\x0e\n\x06thirdq\x18\x05 \x01(\x02\x12\x0f\n\x07std_dev\x18\x06 \x01(\x02\"\x9e\x01\n\x13MarpleFeatureVector\x12\x31\n\x0bqueue_stats\x18\x01 \x01(\x0b\x32\x1c.revelio.StatisticalMeasures\x12\x15\n\rl3_pkt_counts\x18\x02 \x01(\x02\x12\x14\n\x0c\x66rom_packets\x18\x03 \x01(\x02\x12\x12\n\nto_packets\x18\x04 \x01(\x02\x12\x13\n\x0btx_rx_ratio\x18\x05 \x01(\x02\"C\n\x10\x43PUFeatureVector\x12/\n\tcpu_stats\x18\x01 \x01(\x0b\x32\x1c.revelio.StatisticalMeasures\"F\n\x13MemoryFeatureVector\x12/\n\tmem_stats\x18\x01 \x01(\x0b\x32\x1c.revelio.StatisticalMeasures\"z\n\x19RankedMarpleFeatureVector\x12)\n\x03vec\x18\x01 \x01(\x0b\x32\x1c.revelio.MarpleFeatureVector\x12\x18\n\x10rank_queue_depth\x18\x02 \x01(\x02\x12\x18\n\x10rank_tx_rx_ratio\x18\x03 \x01(\x02\"^\n\x16RankedCPUFeatureVector\x12&\n\x03vec\x18\x01 \x01(\x0b\x32\x19.revelio.CPUFeatureVector\x12\x1c\n\x14rank_avg_utilization\x18\x02 \x01(\x02\"d\n\x19RankedMemoryFeatureVector\x12)\n\x03vec\x18\x01 \x01(\x0b\x32\x1c.revelio.MemoryFeatureVector\x12\x1c\n\x14rank_avg_utilization\x18\x02 \x01(\x02\"\x1f\n\rFeatureVector\x12\x0e\n\x06values\x18\x01 \x03(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STATISTICALMEASURES = _descriptor.Descriptor(
  name='StatisticalMeasures',
  full_name='revelio.StatisticalMeasures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='avg', full_name='revelio.StatisticalMeasures.avg', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='revelio.StatisticalMeasures.max', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='median', full_name='revelio.StatisticalMeasures.median', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firstq', full_name='revelio.StatisticalMeasures.firstq', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thirdq', full_name='revelio.StatisticalMeasures.thirdq', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='std_dev', full_name='revelio.StatisticalMeasures.std_dev', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=146,
)


_MARPLEFEATUREVECTOR = _descriptor.Descriptor(
  name='MarpleFeatureVector',
  full_name='revelio.MarpleFeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_stats', full_name='revelio.MarpleFeatureVector.queue_stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l3_pkt_counts', full_name='revelio.MarpleFeatureVector.l3_pkt_counts', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from_packets', full_name='revelio.MarpleFeatureVector.from_packets', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_packets', full_name='revelio.MarpleFeatureVector.to_packets', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tx_rx_ratio', full_name='revelio.MarpleFeatureVector.tx_rx_ratio', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=307,
)


_CPUFEATUREVECTOR = _descriptor.Descriptor(
  name='CPUFeatureVector',
  full_name='revelio.CPUFeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu_stats', full_name='revelio.CPUFeatureVector.cpu_stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=376,
)


_MEMORYFEATUREVECTOR = _descriptor.Descriptor(
  name='MemoryFeatureVector',
  full_name='revelio.MemoryFeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mem_stats', full_name='revelio.MemoryFeatureVector.mem_stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=448,
)


_RANKEDMARPLEFEATUREVECTOR = _descriptor.Descriptor(
  name='RankedMarpleFeatureVector',
  full_name='revelio.RankedMarpleFeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vec', full_name='revelio.RankedMarpleFeatureVector.vec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank_queue_depth', full_name='revelio.RankedMarpleFeatureVector.rank_queue_depth', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank_tx_rx_ratio', full_name='revelio.RankedMarpleFeatureVector.rank_tx_rx_ratio', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=572,
)


_RANKEDCPUFEATUREVECTOR = _descriptor.Descriptor(
  name='RankedCPUFeatureVector',
  full_name='revelio.RankedCPUFeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vec', full_name='revelio.RankedCPUFeatureVector.vec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank_avg_utilization', full_name='revelio.RankedCPUFeatureVector.rank_avg_utilization', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=668,
)


_RANKEDMEMORYFEATUREVECTOR = _descriptor.Descriptor(
  name='RankedMemoryFeatureVector',
  full_name='revelio.RankedMemoryFeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vec', full_name='revelio.RankedMemoryFeatureVector.vec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank_avg_utilization', full_name='revelio.RankedMemoryFeatureVector.rank_avg_utilization', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=770,
)


_FEATUREVECTOR = _descriptor.Descriptor(
  name='FeatureVector',
  full_name='revelio.FeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='revelio.FeatureVector.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=772,
  serialized_end=803,
)

_MARPLEFEATUREVECTOR.fields_by_name['queue_stats'].message_type = _STATISTICALMEASURES
_CPUFEATUREVECTOR.fields_by_name['cpu_stats'].message_type = _STATISTICALMEASURES
_MEMORYFEATUREVECTOR.fields_by_name['mem_stats'].message_type = _STATISTICALMEASURES
_RANKEDMARPLEFEATUREVECTOR.fields_by_name['vec'].message_type = _MARPLEFEATUREVECTOR
_RANKEDCPUFEATUREVECTOR.fields_by_name['vec'].message_type = _CPUFEATUREVECTOR
_RANKEDMEMORYFEATUREVECTOR.fields_by_name['vec'].message_type = _MEMORYFEATUREVECTOR
DESCRIPTOR.message_types_by_name['StatisticalMeasures'] = _STATISTICALMEASURES
DESCRIPTOR.message_types_by_name['MarpleFeatureVector'] = _MARPLEFEATUREVECTOR
DESCRIPTOR.message_types_by_name['CPUFeatureVector'] = _CPUFEATUREVECTOR
DESCRIPTOR.message_types_by_name['MemoryFeatureVector'] = _MEMORYFEATUREVECTOR
DESCRIPTOR.message_types_by_name['RankedMarpleFeatureVector'] = _RANKEDMARPLEFEATUREVECTOR
DESCRIPTOR.message_types_by_name['RankedCPUFeatureVector'] = _RANKEDCPUFEATUREVECTOR
DESCRIPTOR.message_types_by_name['RankedMemoryFeatureVector'] = _RANKEDMEMORYFEATUREVECTOR
DESCRIPTOR.message_types_by_name['FeatureVector'] = _FEATUREVECTOR

StatisticalMeasures = _reflection.GeneratedProtocolMessageType('StatisticalMeasures', (_message.Message,), dict(
  DESCRIPTOR = _STATISTICALMEASURES,
  __module__ = 'feature_vectors_pb2'
  # @@protoc_insertion_point(class_scope:revelio.StatisticalMeasures)
  ))
_sym_db.RegisterMessage(StatisticalMeasures)

MarpleFeatureVector = _reflection.GeneratedProtocolMessageType('MarpleFeatureVector', (_message.Message,), dict(
  DESCRIPTOR = _MARPLEFEATUREVECTOR,
  __module__ = 'feature_vectors_pb2'
  # @@protoc_insertion_point(class_scope:revelio.MarpleFeatureVector)
  ))
_sym_db.RegisterMessage(MarpleFeatureVector)

CPUFeatureVector = _reflection.GeneratedProtocolMessageType('CPUFeatureVector', (_message.Message,), dict(
  DESCRIPTOR = _CPUFEATUREVECTOR,
  __module__ = 'feature_vectors_pb2'
  # @@protoc_insertion_point(class_scope:revelio.CPUFeatureVector)
  ))
_sym_db.RegisterMessage(CPUFeatureVector)

MemoryFeatureVector = _reflection.GeneratedProtocolMessageType('MemoryFeatureVector', (_message.Message,), dict(
  DESCRIPTOR = _MEMORYFEATUREVECTOR,
  __module__ = 'feature_vectors_pb2'
  # @@protoc_insertion_point(class_scope:revelio.MemoryFeatureVector)
  ))
_sym_db.RegisterMessage(MemoryFeatureVector)

RankedMarpleFeatureVector = _reflection.GeneratedProtocolMessageType('RankedMarpleFeatureVector', (_message.Message,), dict(
  DESCRIPTOR = _RANKEDMARPLEFEATUREVECTOR,
  __module__ = 'feature_vectors_pb2'
  # @@protoc_insertion_point(class_scope:revelio.RankedMarpleFeatureVector)
  ))
_sym_db.RegisterMessage(RankedMarpleFeatureVector)

RankedCPUFeatureVector = _reflection.GeneratedProtocolMessageType('RankedCPUFeatureVector', (_message.Message,), dict(
  DESCRIPTOR = _RANKEDCPUFEATUREVECTOR,
  __module__ = 'feature_vectors_pb2'
  # @@protoc_insertion_point(class_scope:revelio.RankedCPUFeatureVector)
  ))
_sym_db.RegisterMessage(RankedCPUFeatureVector)

RankedMemoryFeatureVector = _reflection.GeneratedProtocolMessageType('RankedMemoryFeatureVector', (_message.Message,), dict(
  DESCRIPTOR = _RANKEDMEMORYFEATUREVECTOR,
  __module__ = 'feature_vectors_pb2'
  # @@protoc_insertion_point(class_scope:revelio.RankedMemoryFeatureVector)
  ))
_sym_db.RegisterMessage(RankedMemoryFeatureVector)

FeatureVector = _reflection.GeneratedProtocolMessageType('FeatureVector', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREVECTOR,
  __module__ = 'feature_vectors_pb2'
  # @@protoc_insertion_point(class_scope:revelio.FeatureVector)
  ))
_sym_db.RegisterMessage(FeatureVector)


# @@protoc_insertion_point(module_scope)
